version: "3.1"
services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: unless-stopped
    command: '-u "user;yourpassword" -s "media;/media;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Montreal:/etc/localtime
      - /media:/media
