version: "3.8"
services:
  windows:
    container_name: windows
    image: dockurr/windows-arm
    restart: unless-stopped
    environment:
      VERSION: "11l"
      VGA: "virtio-gpu"
#      DISK_SIZE: "64G"           # default "64G"
      RAM_SIZE: "1G"              # default "4G"
      CPU_CORES: "1"              # default "2"
      USERNAME: "user"            # default "Docker"
      PASSWORD: "yourpassword"    # default ""
#      REGION: "en-US"            # default "en-US"
#      KEYBOARD: "en-US"          # default "en-US"
#      LANGUAGE: "English"        # default "English"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 38006:8006
      - 33389:3389/tcp
      - 33389:3389/udp
    stop_grace_period: 2m
#    volumes:
      #-  /media/sda1/Temp:/shared/Temp
#    networks:
#      ipvlan:
#        ipv4_address: <ipv4_address>
#networks:
#  ipvlan:
#    external: true
