version: "3.9"

services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    ports:
      - 9000:3000  # Access via http://<pi>:3000
      - 9001:3001  # Access via https://<pi>:3001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - CUSTOM_USER=pi
      - PASSWORD=yourpassword
    volumes:
#      - /home/pi/container/webtop:/config
      - /media/sda1/Downloads:/config/Downloads
    restart: unless-stopped
