version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader-2
    restart: unless-stopped
    ports:
      - 35800:5800
    volumes:
      - "/home/pi/container/jdownloader-2:/config:rw"
      - "/media/sda1/Downloads:/output:rw"
