version: "3.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - 32400:32400
#      - 32469:32469
#      - 1900:1900
#      - 3005:3005
#      - 5353:5353
#      - 8324:8324
#      - 32410:32410
#      - 32412:32412
#      - 32413:32413
#      - 32414:32414
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/pi/container/plex:/config
      - /media/sda1/GoogleDrive/Videos:/Videos
      - /etc/localtime:/etc/localtime:ro                    # Sync container time with host timezone
      - /etc/timezone:/etc/timezone:ro                      # Sync container time with host timezone
    restart: unless-stopped
#    networks:
#      ipvlan:
#        ipv4_address: <ipv4_address>
#networks:
#  ipvlan:
#    external: true
