version: "3.9"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 30080:80
    volumes:
      - /home/pi/container/filebrowser:/config  # Config volume to persist user settings
      - /home/pi:/srv/home                      #Shared directory
      - /media/sda1:/srv/usb                    #Shared directory 
    environment:
      - PUID=1000
      - PGID=1000
