version: '3.8'

services:
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 38123:8123
    volumes:
      - /home/pi/container/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
