version: "3.9"

services:
  haproxy-postgres:
    image: haproxy:latest
    container_name: haproxy-postgres
    ports:
      - 5430:5430
    volumes:
      - /home/pi/container/haproxy-postgres/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
