version: '3.8'

services:
  airflow:
    image: apache/airflow:latest                            # image: apache/airflow:3.0.3
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@<postgres_ip_address>:35432/airflow #replace <username>:<password>@<postgres_ip_address>:<postgres_port>/<database>
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: your_secret_key
    ports:
      - 38080:8080
    volumes:
      - /home/pi/container/airflow/dags:/opt/airflow/dags
      - /etc/localtime:/etc/localtime:ro                    # Sync container time with host timezone
      - /etc/timezone:/etc/timezone:ro                      # Sync container time with host timezone
    command: airflow standalone
    restart: unless-stopped
