# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
       MARIADB_ROOT_PASSWORD: example
    ports:
      - 33306:3306
    volumes:
      - /usr/share/zoneinfo/America/Montreal:/etc/localtime

#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 9090:8080
