version: "3.8"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp=unconfined  # Optional
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/container/firefox/config:/config
    ports:
      - 33000:3000
      - 33001:3001
    shm_size: "1gb"
    restart: unless-stopped
