version: "3.1"
services:
  portainer-ce:
    ports:
      - 8000:8000
      - 9443:9443
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
#      - /usr/share/zoneinfo/America/Montreal:/etc/localtime
    image: portainer/portainer-ce:latest
volumes:
  portainer_data:
    external:
      name: portainer_data
