version: "3.1"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 38000:8000
      - 39443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/localtime:/etc/localtime:ro                    # Sync container time with host localtime
      - /etc/timezone:/etc/timezone:ro                      # Sync container time with host timezone
volumes:
  portainer_data:
    external:
      name: portainer_data
