# WARNING: The following commands/images are only for x86_64 systems.
# They will fail on Raspberry Pi or other ARM-based devices.
version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    restart: unless-stopped
    ports:
      - 1433:1433
#    network_mode: host
#    volumes:
#      - /home/pi/container/sqlserver/data:/var/opt/mssql
