# WARNING: SQL Server container is only for x86_64 systems or Apple Silicon.
version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=YourStrongPassword123!
    restart: unless-stopped
    ports:
      - 31433:1433
    volumes:
      - /Users/aldo/Downloads/container/sqlserver/var/opt/mssql/backup:/var/opt/mssql/backup
#      - /home/pi/container/sqlserver/data:/var/opt/mssql
