version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/Montreal
    ports:
      - 35432:5432
    volumes:
      - /home/pi/container/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro                    # Sync container time with host timezone
      - /etc/timezone:/etc/timezone:ro                      # Sync container time with host timezone
