version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/Montreal
    volumes:
      - /home/pi/container/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
